# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    secrets.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyechoi <hyechoi@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/05/05 19:56:13 by hyechoi           #+#    #+#              #
#    Updated: 2021/05/05 19:56:24 by hyechoi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Secret
metadata:
  name: ft-mysql-root-pass
type: Opaque
data:
  password: dDNzdDFzYjN0dDNydGg0bnRoMW5r
---
apiVersion: v1
kind: Secret
metadata:
  name: ft-mysql-wordpressuser-pass
type: Opaque
data:
  password: dDNzdDFzZzAwZA==
