# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    manifest.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyechoi <hyechoi@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/06 13:50:44 by hyechoi           #+#    #+#              #
#    Updated: 2021/04/28 16:17:05 by hyechoi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Secret
metadata:
  name: ft-mysql-root-pass
type: Opaque
data:
  password: dDNzdDFzYjN0dDNydGg0bnRoMW5r
---
apiVersion: v1
kind: Secret
metadata:
  name: ft-mysql-wordpressuser-pass
type: Opaque
data:
  password: dDNzdDFzZzAwZA==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ft-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ft-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ft-mysql
  labels:
    app: ft-mysql
spec:
  type: ClusterIP
  ports:
  - name: mysql-db
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: ft-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-mysql
spec:
  selector:
    matchLabels:
      app: ft-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft-mysql
    spec:
      containers:
      - image: alpine:ft-mysql
        name: ft-mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-mysql-root-pass
                key: password
          - name: MYSQL_WORDPRESSUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-mysql-wordpressuser-pass
                key: password
        ports:
        - containerPort: 3306
          name: ft-mysql
        volumeMounts:
        - name: ft-mysql-pv-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: ft-mysql-pv-volume
        persistentVolumeClaim:
          claimName: ft-mysql-pv-claim
