# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    manifest.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyechoi <hyechoi@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/06 13:50:44 by hyechoi           #+#    #+#              #
#    Updated: 2021/05/22 17:34:05 by hyechoi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: ft-grafana
  labels:
    run: ft-grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: https
  selector:
    run: ft-grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-grafana
spec:
  selector:
    matchLabels:
      run: ft-grafana
  replicas: 1
  template:
    metadata:
      labels:
        run: ft-grafana
    spec:
      containers:
      - name: ft-grafana
        image: alpine:ft-grafana
        env:
          - name: GRAFANA_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-grafana-root-pass
                key: username
          - name: GRAFANA_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-grafana-root-pass
                key: password
          - name: INFLUXDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-root-pass
                key: username
          - name: INFLUXDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-root-pass
                key: password
          - name: INFLUXDB_ROOT_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-root-pass
                key: database
          - name: INFLUXDB_FT_NGINX_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-nginx-pass
                key: username
          - name: INFLUXDB_FT_NGINX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-nginx-pass
                key: password
          - name: INFLUXDB_FT_NGINX_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-nginx-pass
                key: database
          - name: INFLUXDB_FT_PHPMYADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-phpmyadmin-pass
                key: username
          - name: INFLUXDB_FT_PHPMYADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-phpmyadmin-pass
                key: password
          - name: INFLUXDB_FT_PHPMYADMIN_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-phpmyadmin-pass
                key: database
          - name: INFLUXDB_FT_WORDPRESS_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-wordpress-pass
                key: username
          - name: INFLUXDB_FT_WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-wordpress-pass
                key: password
          - name: INFLUXDB_FT_WORDPRESS_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-wordpress-pass
                key: database
          - name: INFLUXDB_FT_MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-mysql-pass
                key: username
          - name: INFLUXDB_FT_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-mysql-pass
                key: password
          - name: INFLUXDB_FT_MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-mysql-pass
                key: database
          - name: INFLUXDB_FT_FTPS_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-ftps-pass
                key: username
          - name: INFLUXDB_FT_FTPS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-ftps-pass
                key: password
          - name: INFLUXDB_FT_FTPS_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-ftps-pass
                key: database
          - name: INFLUXDB_FT_GRAFANA_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-grafana-pass
                key: username
          - name: INFLUXDB_FT_GRAFANA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-grafana-pass
                key: password
          - name: INFLUXDB_FT_GRAFANA_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-grafana-pass
                key: database
          - name: INFLUXDB_FT_INFLUXDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-influxdb-pass
                key: username
          - name: INFLUXDB_FT_INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-influxdb-pass
                key: password
          - name: INFLUXDB_FT_INFLUXDB_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-influxdb-pass
                key: database
        ports:
        - containerPort: 3000
