# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    manifest.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyechoi <hyechoi@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/06 13:50:44 by hyechoi           #+#    #+#              #
#    Updated: 2021/05/22 23:50:43 by hyechoi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: ft-nginx
  labels:
    run: ft-nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    run: ft-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-nginx
spec:
  selector:
    matchLabels:
      run: ft-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: ft-nginx
    spec:
      containers:
      - name: ft-nginx
        image: alpine:ft-nginx
        env:
          - name: INFLUXDB_FT_NGINX_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-nginx-pass
                key: username
          - name: INFLUXDB_FT_NGINX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-nginx-pass
                key: password
          - name: INFLUXDB_FT_NGINX_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-nginx-pass
                key: database
        ports:
        - containerPort: 443
        - containerPort: 80
