# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    manifest.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyechoi <hyechoi@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/06 13:50:44 by hyechoi           #+#    #+#              #
#    Updated: 2021/05/22 23:54:46 by hyechoi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: ft-phpmyadmin
  labels:
    app: ft-phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: https
  selector:
    app: ft-phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-phpmyadmin
spec:
  selector:
    matchLabels:
      app: ft-phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: ft-phpmyadmin
    spec:
      containers:
      - name: ft-phpmyadmin
        image: alpine:ft-phpmyadmin
        env:
          - name: MYSQL_PMA_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: ft-mysql-pma-pass
                key: password
          - name: INFLUXDB_FT_PHPMYADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-phpmyadmin-pass
                key: username
          - name: INFLUXDB_FT_PHPMYADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-phpmyadmin-pass
                key: password
          - name: INFLUXDB_FT_PHPMYADMIN_DATABASE
            valueFrom:
              secretKeyRef:
                name: ft-influxdb-ft-phpmyadmin-pass
                key: database
        ports:
        - containerPort: 5000
