apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
    annotations:
        metallb.universe.tf/allow-shared-ip: shared
data:
    config: |
        address-pools:
        -   name: default
            protocol: layer2
            addresses:
            -   MINIKUBE_IP-MINIKUBE_IP
