# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    manifest.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyechoi <hyechoi@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/06 13:50:44 by hyechoi           #+#    #+#              #
#    Updated: 2021/05/18 17:13:35 by hyechoi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: ft-wordpress
  labels:
    app: ft-wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
    name: https
  selector:
    app: ft-wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-wordpress
spec:
  selector:
    matchLabels:
      app: ft-wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: ft-wordpress
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      containers:
      - name: ft-wordpress
        image: alpine:ft-wordpress
        env:
          - name: MYSQL_WORDPRESSUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-mysql-wordpressuser-pass
                key: password
          - name: FT_WORDPRESS_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-admin-pass
                key: username
          - name: FT_WORDPRESS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-admin-pass
                key: password
          - name: FT_WORDPRESS_USER_ALICE_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-alice-pass
                key: username
          - name: FT_WORDPRESS_USER_ALICE_EMAIL
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-alice-pass
                key: email
          - name: FT_WORDPRESS_USER_ALICE_DISPLAY_NAME
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-alice-pass
                key: display_name
          - name: FT_WORDPRESS_USER_ALICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-alice-pass
                key: password
          - name: FT_WORDPRESS_USER_BOB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-bob-pass
                key: username
          - name: FT_WORDPRESS_USER_BOB_EMAIL
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-bob-pass
                key: email
          - name: FT_WORDPRESS_USER_BOB_DISPLAY_NAME
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-bob-pass
                key: display_name
          - name: FT_WORDPRESS_USER_BOB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-bob-pass
                key: password
          - name: FT_WORDPRESS_USER_MARY_USERNAME
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-mary-pass
                key: username
          - name: FT_WORDPRESS_USER_MARY_EMAIL
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-mary-pass
                key: email
          - name: FT_WORDPRESS_USER_MARY_DISPLAY_NAME
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-mary-pass
                key: display_name
          - name: FT_WORDPRESS_USER_MARY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-wordpress-user-mary-pass
                key: password
        ports:
        - containerPort: 5050
          name: ft-wordpress
