# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
deleteDatasources:
  - name: ft-nginx
    orgId: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
   # <string, required> name of the datasource. Required
  - name: ft-nginx
#   # <string, required> datasource type. Required
    type: influxdb
#   # <string, required> access mode. direct or proxy. Required
    access: proxy
#   # <bool> allow users to edit datasources from the UI.
    editable: false
#   # <int> org id. will default to orgId 1 if not specified
    orgId: 1
#   # <string> url
    url: http://ft-influxdb:8086
    version: 1
#   # <string> database user, if used
#    user:
#   # <string> database password, if used
#    password:
#   # <string> database name, if used
#    database:
